spring:
  application:
    name: service-auth-v1
  profiles:
    active:
      - local

  web:
    locale: zh_CN
  webflux:
    format:
      date: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  session:
    timeout: 7D
    store-type: none
    mongodb:
      collection-name: sessions
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_empty
    property-naming-strategy: UPPER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATE_KEYS_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${hfhk.auth.server:auth-server}/oauth2/jwks
  data:
    mongodb:
      auto-index-creation: true
      field-naming-strategy: com.hfhk.cairo.mongo.data.mapping.model.UpperCamelCaseFieldNamingStrategy
      database: ${hfhk.mongo.database:hfhk-auth}
      gridfs:
        database: ${hfhk.mongo.gridfs.database:hfhk-auth}
      host: ${hfhk.mongo.host:mongo}
      port: ${hfhk.mongo.port:27017}
      username: ${hfhk.mongo.username:hfhk}
      password: ${Hfhk.mongo.password:Hfhk.1320.}
      authentication-database: ${hfhk.mongo.authentication-database:hfhk}
  redis:
    database: 10
    host: 192.168.30.21
    port: 6379
    password: Hfhk-!@#-1230.
    timeout: 10s
    lettuce:
      shutdown-timeout: 5000ms
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cloud:
    consul:
      host: ${hfhk.consul.host:localhost}
      port: ${hfhk.consul.port:8500}
      discovery:
        prefer-ip-address: true
        health-check-interval: 5s
        instance-zone: ${hfhk.consul.discovery.instance-zone:hfhk}
        instance-group: ${hfhk.consul.discovery.instance-group:hfhk}
        tags:
          - v1
server:
  port: 80
  http2:
    enabled: true
  servlet:
    encoding:
      force: true


security:
  oauth2:
    client:
      id: ${random.value}
      client-id: ${hfhk.auth.client.id:hfhk_auth}
      client-secret: ${hfhk.auth.client.id:hfhk_auth}
      grant-type: client_credentials
      access-token-uri: http://${hfhk.auth.server:auth-server}/oauth2/token

feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 60000
  compression:
    request:
      min-request-size: 204000
  client:
    default-to-properties: true
    config:
      default:
        logger-level: FULL


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'


logging:
  level:
    root: info
    com.hfhk: debug
  file:
    name: /hfhk/auth/service/logs/hfhk.log
