spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      authentication-database: ${MONGO_AUTHENTICATION_DATABSE:cairo}
      username: ${MONGO_USERNAME:cairo}
      password: ${MONGO_PASSWORD:Hfhk-cairo-!@#-1230.}
      database: ${MONGO_DATABSE:cairo-auth}

      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_ADDR:auth}/.well-known/jwks.json
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      discovery:
        server-addr: ${NACOS_DISCOVERY_SERVER_ADDR:${NACOS_SERVER_ADDR:localhost:8848}}
        namespace: ${NACOS_DISCOVERY_NAMESPACE:${NACOS_NAMESPACE:cairo}}
        group: ${NACOS_DISCOVERY_GROUP:${NACOS_GROUP:cairo}}
      # config:
      #   server-addr: ${NACOS_CONFIG_SERVER_ADDR:${NACOS_SERVER_ADDR:localhost:8848}}
      #   namespace: ${NACOS_CONFIG_NAMESPACE:${NACOS_NAMESPACE:cairo}}
      #   group: ${NACOS_CONFIG_GROUP:${NACOS_GROUP:cairo}}
      #   file-extension: yaml

security:
  oauth2:
    client:
      id: ${OAUTH_CLIENT_ID:cairo_service_auth}
      client-id: ${OAUTH_CLIENT_ID:cairo_service_auth}
      client-secret: ${OAUTH2_CLIENT_SECRET:cairo_service_auth}
      grant-type: client_credentials
      access-token-uri: http://${AUTH_ADDR:auth}/oauth/token

server:
  port: 80

logging:
  level:
    com.hfhk.cairo: debug
  file:
    name: /hfhk/cairo/service/auth/logs/hfhk.log
